from __future__ import annotations

from enum import Enum


# DD-04: state placeholders only
class PortfolioState(str, Enum):
    INIT = "INIT"
    INTAKE_COMPLETE = "INTAKE_COMPLETE"
    PORTFOLIO_INTEGRITY_READY = "PORTFOLIO_INTEGRITY_READY"
    PORTFOLIO_CONTEXT_READY = "PORTFOLIO_CONTEXT_READY"
    HOLDING_EVALUATION_IN_PROGRESS = "HOLDING_EVALUATION_IN_PROGRESS"
    HOLDING_EVALUATION_COMPLETE = "HOLDING_EVALUATION_COMPLETE"
    AGGREGATION_READY = "AGGREGATION_READY"
    FINALIZATION_READY = "FINALIZATION_READY"
    COMPLETED = "COMPLETED"
    VETOED = "VETOED"
    FAILED = "FAILED"
    SHORT_CIRCUITED = "SHORT_CIRCUITED"


class HoldingState(str, Enum):
    HOLDING_PENDING = "HOLDING_PENDING"
    HOLDING_IDENTITY_VALIDATED = "HOLDING_IDENTITY_VALIDATED"
    HOLDING_DATA_INTEGRITY_READY = "HOLDING_DATA_INTEGRITY_READY"
    HOLDING_EVALUATION_IN_PROGRESS = "HOLDING_EVALUATION_IN_PROGRESS"
    HOLDING_EVALUATION_COMPLETE = "HOLDING_EVALUATION_COMPLETE"
    HOLDING_COMPLETED = "HOLDING_COMPLETED"
    HOLDING_VETOED = "HOLDING_VETOED"
    HOLDING_FAILED = "HOLDING_FAILED"
    HOLDING_SHORT_CIRCUITED = "HOLDING_SHORT_CIRCUITED"
