# DD-06: governance precedence constants only
DIO_VETO = "DIO_VETO"
GRRA_SHORT_CIRCUIT = "GRRA_SHORT_CIRCUIT"
RISK_OFFICER_VETO = "RISK_OFFICER_VETO"
LEFO_CAP = "LEFO_CAP"
PSCC_CAP = "PSCC_CAP"
PENALTIES = "PENALTIES"
CHAIR = "CHAIR"
